export const ADD_NEW_HOTDOG = 'ADD_NEW_HOTDOG';
export const EDIT_HOTDOG = 'EDIT_HOTDOG';
export const UPGRADE_HOTDOG = 'UPGRADE_HOTDOG';
export const DELETE_HOTDOG = 'DELETE_HOTDOG';
export const UPDATE_HOTDOG = 'UPDATE_HOTDOG';
export const SHOW_HIDE_MODAL = 'SHOW_HIDE_MODAL';